services:
  ubu100:
    image: iacplayground
    stdin_open: true
    hostname: ubu100
    working_dir: /home/ubuntu
    entrypoint: bash -c 'service ssh restart && bash'
    expose:
      - "22"
    networks:
      ans_test:
        ipv4_address: 172.16.238.100
        ipv6_address: 2001:3984:3989::100
    
  ubu101:
    image: iacplayground
    stdin_open: true
    hostname: ubu101
    working_dir: /home/ubuntu
    entrypoint: bash -c 'service ssh restart && bash'
    expose:
      - "22"
    networks:
      ans_test:
        ipv4_address: 172.16.238.101
        ipv6_address: 2001:3984:3989::101
  
  ubu102:
    image: iacplayground
    stdin_open: true
    hostname: ubu102
    working_dir: /home/ubuntu
    entrypoint: bash -c 'service ssh restart && bash'
    expose:
      - "22"
    networks:
      ans_test:
        ipv4_address: 172.16.238.102
        ipv6_address: 2001:3984:3989::102

  ubu103:
    image: iacplayground
    stdin_open: true
    hostname: ubu103
    working_dir: /home/ubuntu
    entrypoint: bash -c 'service ssh restart && bash'
    expose:
      - "22"
    networks:
      ans_test:
        ipv4_address: 172.16.238.103
        ipv6_address: 2001:3984:3989::103

networks:
  ans_test:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"