- hosts: mycloud
  # vars_files:
  #   - secrets/secrets.yml
  become: yes
  tasks:
    - name: Update ubuntu 
      apt:
        update_cache: yes

    - name: Upgrade all packages on servers
      apt: 
        name: "*"
        state: latest
        autoremove: yes